spring:
  datasource:
    username: demo1
    password: demo1
    url: jdbc:mysql://localhost:3306/demo1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo1.entity
logging:
  level:
    com:
      example:
        demo1:
          dao: debug

jaign:
  config:
    free-space-root: C:/Users/jaign/test/